version: '3.8'

services:
  app:
    container_name: jira
    image: jira
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - secret_data.env
    networks:
      - backend

  db:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - secret_data.env
    healthcheck:
        test: pg_isready -h localhost -U $$POSTGRES_USER
        interval: 5s
        timeout: 5s
        retries: 5
        start_period: 5s
    networks:
      - backend

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
    depends_on:
      app:
        condition: service_started

networks:
  backend:
    driver: bridge